import axios from 'axios'

export const FETCHING_SAVED_WORKOUTS = 'FETCHING_SAVED_WORKOUTS'
export const FETCH_SAVED_WORKOUTS = 'FETCH_SAVED_WORKOUTS'
export const FETCH_CURRENT_WORKOUTS = 'FETCH_CURRENT_WORKOUTS'
